// react/antd/src/layouts/app/components/footer.tsx
import { Flex, Typography } from 'antd';
import React from 'react';

const Footer: React.FC = () => {
  return (
    <Flex justify="space-between" align="center">
      <Typography.Text type="secondary">
        © {new Date().getFullYear()} runow.dev
      </Typography.Text>
      <Typography.Text type="secondary">
        Powered by <a href="https://runow.dev">Runow</a>
      </Typography.Text>
    </Flex>
  );
};

export default Footer;

// vue/vite/antdv/src/layouts/root/components/footer.vue
<script setup lang="ts">
const appName = import.meta.env.VITE_APP_NAME;
</script>

<template>
  <a-flex align="center" justify="space-between">
    <a-typography-text type="secondary">
      © {{ new Date().getFullYear() }} {{ appName }}
    </a-typography-text>
    <a-typography-text type="secondary"> Powered by Runow </a-typography-text>
  </a-flex>
</template>

<style scoped></style>
