// vue/antdv/src/views/auth/login/index.vue
<script setup lang="ts"></script>

<template>
  <a-typography-title :level="2">Welcome Back</a-typography-title>
  <a-typography-paragraph type="secondary">
    Don't have an account? <router-link to="/signup">Signup Now →</router-link>
  </a-typography-paragraph>
  <a-form layout="vertical">
    <a-form-item label="Username" name="username">
      <a-input size="large" placeholder="Username" />
    </a-form-item>
    <a-form-item label="Password" name="password">
      <a-input-password size="large" placeholder="Password" />
    </a-form-item>
    <a-form-item>
      <a-flex justify="space-between" align="center">
        <a-form-item name="remember" no-style>
          <a-checkbox>Remember me</a-checkbox>
        </a-form-item>
        <router-link to="/forgot-password">Forgot password?</router-link>
      </a-flex>
    </a-form-item>
    <a-form-item>
      <a-button html-type="submit" type="primary" size="large" block>
        Log in
      </a-button>
    </a-form-item>
  </a-form>
</template>

<style scoped></style>

// react/vite/antd/src/pages/auth/login/index.tsx
import { authService } from '@/pages/auth/services';
import { title } from '@/utils/document';
import { useRequest } from 'ahooks';
import {
  Alert,
  Button,
  Checkbox,
  Flex,
  Form,
  type FormProps,
  Input,
  Typography,
} from 'antd';
import { useState } from 'react';
import { Link, useNavigate } from 'react-router';

export function meta() {
  return [{ title: title('Sign In') }];
}

export default function Index() {
  const [form] = Form.useForm();
  const navigate = useNavigate();
  const [errMsg, setErrMsg] = useState<string>();

  const { loading: submitting, run: doSubmit } = useRequest(authService.login, {
    manual: true,
    onSuccess: (data) => {
      // const { token } = data;
      // setToken(token);
      setErrMsg(undefined);
    },
    onError: (e) => {
      setErrMsg(e.message);
    },
  });

  const onFinish: FormProps['onFinish'] = (values) => {
    // check login and then set token, eg:
    // doSubmit(values);

    // demo skip
    navigate('/', { replace: true });
  };

  return (
    <>
      <Typography.Title level={2}>Welcome back</Typography.Title>
      <Typography.Paragraph type="secondary">
        Don't have an account? <Link to="/signup">Signup Now →</Link>
      </Typography.Paragraph>
      {errMsg && (
        <Alert
          message={errMsg}
          type="error"
          showIcon
          style={{ marginBottom: 16 }}
        />
      )}
      <Form
        form={form}
        layout="vertical"
        size="large"
        variant="filled"
        requiredMark={false}
        onFinish={onFinish}
      >
        <Form.Item
          label="Username"
          name="username"
          rules={[
            {
              required: true,
              message: 'Username is required',
            },
          ]}
        >
          <Input placeholder="Username/Email" />
        </Form.Item>
        <Form.Item
          label="Password"
          name="password"
          rules={[
            {
              required: true,
              message: 'Password is required',
            },
          ]}
        >
          <Input.Password placeholder="Password" />
        </Form.Item>
        <Form.Item>
          <Flex justify="space-between" align="center">
            <Form.Item name="remember" noStyle valuePropName="checked">
              <Checkbox>Remember me</Checkbox>
            </Form.Item>
            <Link to="/forgot-password">Forgot password?</Link>
          </Flex>
        </Form.Item>
        <Form.Item>
          <Button block type="primary" htmlType="submit" loading={submitting}>
            Log in
          </Button>
        </Form.Item>
      </Form>
    </>
  );
}
