// vue/antdv/src/layouts/auth/index.vue
<script setup lang="ts">
const appName = import.meta.env.VITE_APP_NAME;
</script>

<template>
  <a-layout class="root">
    <a-layout class="wrap">
      <a-layout-header class="header">
        <a-avatar shape="square">LOGO</a-avatar>
      </a-layout-header>
      <a-layout-content class="content">
        <div class="container">
          <router-view />
        </div>
      </a-layout-content>
      <a-layout-footer class="footer">
        <a-typography-text type="secondary">
          © {{ new Date().getFullYear() }} {{ appName }}
        </a-typography-text>
      </a-layout-footer>
    </a-layout>
    <a-layout-sider
      class="banner"
      breakpoint="lg"
      :collapsed-width="0"
      width="33%"
    >
      <div class="backdrop"></div>
    </a-layout-sider>
  </a-layout>
</template>

<style scoped>
.root {
  min-height: 100vh;
  background: transparent;
}
.wrap {
  background: transparent;
}
.header {
  background: transparent;
  padding: 32px;
  height: auto;
  line-height: 1;
}
.content {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
}
.container {
  max-width: 400px;
  width: 100%;
  padding: 16px;
}
.footer {
  text-align: center;
  background: transparent;
}
.backdrop {
  display: block;
  width: 100%;
  height: 100%;
  background-repeat: no-repeat;
  background-position: center;
  background-size: cover;
  background-image: url('@/assets/images/sso.jpg');
}
</style>

// react/antd/src/layouts/auth/index.tsx
import bannerUrl from '@/assets/images/sso.jpg';
import { Avatar, ConfigProvider, Layout, Typography } from 'antd';
import { createStyles, useResponsive } from 'antd-style';
import React from 'react';
import { Outlet } from 'react-router';

const useStyles = createStyles(({ css, token, prefixCls }) => {
  return {
    root: css`
      min-height: 100vh;
    `,
    header: css`
      height: auto;
      line-height: 1;
      padding: ${token.paddingLG}px;
    `,
    wrap: css`
      background-color: ${token.colorBgContainer};
    `,
    content: css`
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
    `,
    footer: css`
      text-align: center;
    `,
    sider: css`
      .${prefixCls}-layout-sider-children > div {
        display: block;
        width: 100%;
        height: 100%;
        background-repeat: no-repeat;
        background-position: center;
        background-size: cover;
      }
    `,
    container: css`
      max-width: ${token.screenXS}px;
      width: 100%;
      padding: ${token.padding}px;
    `,
  };
});

const AuthLayout: React.FC = () => {
  const { styles } = useStyles();

  // 避免移动设备banner栏闪烁
  const { laptop: showBanner } = useResponsive();
  return (
    <ConfigProvider
      theme={{
        components: {
          Layout: {
            headerBg: 'transparent',
            footerBg: 'transparent',
          },
        },
      }}
    >
      <Layout className={styles.root} hasSider={showBanner}>
        <Layout className={styles.wrap}>
          <Layout.Header className={styles.header}>
            <Avatar shape="square" src="/runow.svg" />
          </Layout.Header>
          <Layout.Content className={styles.content}>
            <div className={styles.container}>
              <Outlet />
            </div>
          </Layout.Content>
          <Layout.Footer className={styles.footer}>
            <Typography.Text type="secondary">
              © {new Date().getFullYear()} {import.meta.env.VITE_APP_NAME}
            </Typography.Text>
          </Layout.Footer>
        </Layout>
        <Layout.Sider
          className={styles.sider}
          collapsedWidth={0}
          breakpoint="lg"
          width="33%"
          trigger={null}
        >
          <div
            style={{
              backgroundImage: `url(${bannerUrl})`,
            }}
          />
        </Layout.Sider>
      </Layout>
    </ConfigProvider>
  );
};

export default AuthLayout;
