// react/antd/src/components/page-container/index.tsx
import { ConfigProvider, Flex, Menu, type MenuProps, Typography } from 'antd';
import { useTheme } from 'antd-style';
import classNames from 'classnames';
import React from 'react';
import { NavLink } from 'react-router';

export type PageContainerProps = React.PropsWithChildren<{
  title?: React.ReactNode;
  menus?: MenuProps['items'];
}>;

const PageContainer: React.FC<PageContainerProps> = ({
  title,
  menus,
  children,
}) => {
  const { prefixCls } = useTheme();

  return (
    <Flex vertical gap={16}>
      {title && (
        <Typography.Title level={3} style={{ margin: 0 }}>
          {title}
        </Typography.Title>
      )}
      {menus && menus.length > 0 && (
        <ConfigProvider
          theme={{
            components: {
              Menu: {
                itemBg: 'transparent',
                itemPaddingInline: '0 32px',
              },
            },
          }}
        >
          <Menu
            mode="horizontal"
            items={menus}
            _internalRenderMenuItem={(dom, props) => {
              const { elementRef, className, ...reset } = dom.props;
              return (
                <NavLink
                  to={props.eventKey}
                  ref={elementRef}
                  className={({ isActive }) =>
                    classNames(className, {
                      [`${prefixCls}-menu-item-selected`]: isActive,
                    })
                  }
                  viewTransition
                  {...reset}
                />
              );
            }}
          />
        </ConfigProvider>
      )}
      {children}
    </Flex>
  );
};

export default PageContainer;

// vue/antdv/src/components/page-container/index.vue
<script setup lang="ts">
import type { ItemType } from 'ant-design-vue';
import { computed, h } from 'vue';
import { RouterLink } from 'vue-router';

const props = defineProps<{
  title?: string;
  menus?: ItemType[];
  size?: 'small' | 'medium' | 'large';
  showBack?: boolean;
}>();

const generateLabel = (item: any) => {
  return item?.href
    ? h(
        RouterLink,
        {
          to: item.href,
        },
        item.label,
      )
    : item.label;
};

const menuItems = computed(() => {
  return props.menus?.map((menu) => ({
    ...menu,
    label: generateLabel(menu),
  }));
});
</script>

<template>
  <a-flex vertical :gap="16">
    <slot name="title">
      <a-typography-title v-if="props.title" :level="3" class="title">
        {{ props.title }}
      </a-typography-title>
    </slot>
    <slot name="menu">
      <a-menu
        v-if="menuItems"
        :items="menuItems"
        mode="horizontal"
        class="menu"
      />
    </slot>
    <slot />
  </a-flex>
</template>

<style scoped>
.title {
  margin: 0;
}
.menu {
  background: transparent;
}
</style>
