// vue/antdv/src/layouts/root/components/header.vue
<script setup lang="ts">
import {
  BellIcon,
  ChevronDownIcon,
  LogOutIcon,
  MoonIcon,
  ShieldIcon,
  UserIcon,
} from 'lucide-vue-next';
</script>

<template>
  <a-flex justify="space-between" align="center" style="height: 100%">
    <span></span>
    <a-flex :gap="8" align="center">
      <a-button type="text">
        <template #icon>
          <a-icon>
            <bell-icon :size="16" />
          </a-icon>
        </template>
      </a-button>
      <a-button type="text">
        <template #icon>
          <a-icon>
            <moon-icon :size="16" />
          </a-icon>
        </template>
      </a-button>
      <a-dropdown>
        <a-button type="text" class="profile-btn">
          <template #icon>
            <a-avatar src="https://i.pravatar.cc/128?img=12" />
          </template>
          <span>Nickname</span>
          <a-icon>
            <chevron-down-icon :size="14" />
          </a-icon>
        </a-button>
        <template #overlay>
          <a-menu>
            <a-menu-item>
              <a-icon>
                <user-icon :size="16" />
              </a-icon>
              Profile
            </a-menu-item>
            <a-menu-item>
              <a-icon>
                <shield-icon :size="16" />
              </a-icon>
              Security
            </a-menu-item>
            <a-menu-divider />
            <a-menu-item danger>
              <a-icon>
                <log-out-icon :size="16" />
              </a-icon>
              Logout
            </a-menu-item>
          </a-menu>
        </template>
      </a-dropdown>
    </a-flex>
  </a-flex>
</template>

<style scoped>
.profile-btn {
  height: 100%;
  border-radius: 0;
  line-height: 1;
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 8px;
}
</style>

// react/vite/antd/src/layouts/app/components/header.tsx
import ThemeSwitcher from '@/components/theme-switcher';
import { Avatar, Button, Dropdown, Flex, Typography } from 'antd';
import { ThemeProvider } from 'antd-style';
import {
  BellIcon,
  ChevronDownIcon,
  LogOutIcon,
  ShieldIcon,
  UserIcon,
} from 'lucide-react';
import React from 'react';
import { Link } from 'react-router';

const Header: React.FC = () => {
  return (
    <>
      <ThemeProvider themeMode="dark">
        <Typography.Title level={5} style={{ margin: 0 }}>
          LOGO
        </Typography.Title>
      </ThemeProvider>
      <Flex align="center" gap={8}>
        <ThemeProvider themeMode="dark">
          <Button type="text" icon={<BellIcon size={18} />} />
          <ThemeSwitcher />
        </ThemeProvider>
        <Dropdown
          menu={{
            items: [
              {
                key: '/settings/profile',
                label: 'Profile',
                icon: <UserIcon size={16} />,
              },
              {
                key: '/settings/security',
                label: 'Security',
                icon: <ShieldIcon size={16} />,
              },
              {
                type: 'divider',
              },
              {
                key: '/login',
                label: 'Logout',
                icon: <LogOutIcon size={16} />,
                danger: true,
              },
            ],
            _internalRenderMenuItem: (dom, props) => {
              const { elementRef, ...reset } = dom.props;
              return (
                <Link
                  to={props.eventKey}
                  ref={elementRef}
                  viewTransition
                  {...reset}
                />
              );
            },
          }}
        >
          <div>
            <ThemeProvider themeMode="dark">
              <Button
                type="text"
                icon={<ChevronDownIcon size={14} />}
                iconPosition="end"
                style={{
                  height: 48,
                  border: 0,
                  borderRadius: 0,
                }}
              >
                <Flex align="center" gap={8}>
                  <Avatar
                    size="small"
                    shape="square"
                    src="https://i.pravatar.cc/128?img=12"
                  />
                  <Typography.Text>Nickname</Typography.Text>
                </Flex>
              </Button>
            </ThemeProvider>
          </div>
        </Dropdown>
      </Flex>
    </>
  );
};

export default Header;
