// vue/antdv/src/layouts/root/components/sidebar.vue
<script setup lang="ts">
import AntIcon from '@/components/ant-icon/index.vue';
import {
  BoltIcon,
  HomeIcon,
  TriangleAlertIcon,
  UsersIcon,
} from 'lucide-vue-next';
import { type FunctionalComponent, h, ref } from 'vue';
import { RouterLink } from 'vue-router';

const props = defineProps<{
  collapsed?: boolean;
}>();

const generateIcon = (icon: FunctionalComponent) => {
  return h(AntIcon, [
    h(icon, {
      size: 16,
    }),
  ]);
};

const generateLabel = (label: string, link: string) => {
  return h(
    RouterLink,
    {
      to: link,
    },
    label,
  );
};

const menus = ref([
  {
    key: 'home',
    label: generateLabel('Home', '/'),
    title: 'Home',
    icon: () => generateIcon(HomeIcon),
  },
  {
    key: 'users',
    label: generateLabel('Users', '/users'),
    title: 'Users',
    icon: () => generateIcon(UsersIcon),
  },
  {
    key: 'settings',
    label: generateLabel('Settings', '/settings'),
    title: 'Settings',
    icon: () => generateIcon(BoltIcon),
  },
  {
    key: '404',
    label: generateLabel('404', '/xxx'),
    title: '404',
    icon: () => generateIcon(TriangleAlertIcon),
  },
]);
</script>

<template>
  <a-flex vertical class="wrap">
    <a-flex vertical flex="none">
      <a href="/" class="brand">
        <img src="/runow.svg" alt="logo" class="brand-logo" />
        <h1 v-if="!props.collapsed" class="brand-name">LOGO</h1>
      </a>
    </a-flex>
    <a-flex vertical flex="auto" class="menu-wrap">
      <a-menu
        :inline-collapsed="props.collapsed"
        mode="inline"
        :items="menus"
        theme="dark"
        :selectable="false"
      />
    </a-flex>
  </a-flex>
</template>

<style scoped>
.wrap {
  height: 100%;
}
.brand {
  height: 64px;
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 0 16px;
}

.brand-logo {
  display: block;
  width: 32px;
  height: 32px;
}

.brand-name {
  margin: 0;
  font-size: 18px;
  color: #fff;
  line-height: 1;
}

.menu-wrap {
  padding: 0 8px;
}
</style>

// react/vite/antd/src/layouts/app/components/sidebar.tsx
import { type GetProp, Menu, type MenuProps } from 'antd';
import { createStyles } from 'antd-style';
import classNames from 'classnames';
import { BoltIcon, HomeIcon, TriangleAlertIcon, UsersIcon } from 'lucide-react';
import React from 'react';
import { NavLink } from 'react-router';

const useStyles = createStyles(({ css, token, prefixCls }) => {
  return {
    menu: css`
      &.${prefixCls}-menu-light.${prefixCls}-menu-root {
        &.${prefixCls}-menu-inline,&.${prefixCls}-menu-vertical {
          border-inline-end: 0; // remove right border
          max-height: 100%;
          overflow: auto;
          padding: 0;

          // custom scrollbar (recommend)
          &::-webkit-scrollbar {
            width: 4px;
            height: 4px;
          }
          &::-webkit-scrollbar-track {
            background: transparent;
          }
          &::-webkit-scrollbar-thumb {
            background: ${token.colorFill};
            border-radius: 4px;
          }
        }
      }

      // hide group title (recommend)
      &.${prefixCls}-menu-inline-collapsed {
        .${prefixCls}-menu-item-group-title {
          display: none;
        }
      }

      // shrink arrow (¬‿¬)
      .${prefixCls}-menu-submenu-arrow {
        &:before,
        &:after {
          height: 1px;
          border-radius: 0;
        }
      }
    `,
  };
});

type MenuItemType = GetProp<MenuProps, 'items'>[number] & {
  path: string;
};

const menus: MenuItemType[] = [
  // use dynamic icons [not recommended]
  // {
  //   key: 'home',
  //   label: 'Home',
  //   icon: <DynamicIcon name="home" size={16} />,
  //   path: '/',
  // },
  {
    key: 'home',
    label: 'Home',
    icon: <HomeIcon size={16} />,
    path: '/',
  },
  {
    key: 'users',
    label: 'Users',
    icon: <UsersIcon size={16} />,
    path: '/users',
  },
  {
    key: 'settings',
    label: 'Settings',
    icon: <BoltIcon size={16} />,
    path: '/settings',
  },
  {
    key: 'not-found',
    label: '404',
    icon: <TriangleAlertIcon size={16} />,
    path: '/xxx',
  },
];

const Sidebar: React.FC = () => {
  const { styles, prefixCls } = useStyles();

  return (
    <>
      <Menu
        className={styles.menu}
        theme="light"
        mode="inline"
        items={menus}
        selectable={false}
        _internalRenderMenuItem={(dom, props) => {
          const { elementRef, className, ...reset } = dom.props;
          return (
            <NavLink
              to={props.path}
              ref={elementRef}
              viewTransition
              className={({ isActive }) =>
                classNames(className, {
                  [`${prefixCls}-menu-item-selected`]: isActive,
                })
              }
              {...reset}
            />
          );
        }}
      />
    </>
  );
};

export default Sidebar;
